# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reactsample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactsample
  pod 'RNMobileCenter', '~> 0.2.0'
  pod 'MobileCenter', '~> 0.4.0'

  

  target 'reactsampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'reactsample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactsample-tvOS

  target 'reactsample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
